int login();
void enternew();
void removepro();
void makebill();
void additem();
float preview();
void last(float totalam);
void modify();
void removeitem();
void display();
void searching();
void makechange();
void change(char name1[16],int cosqua);
void printother();
int adminlogin();
int searchs(char name[16]);
void statistics();
void printstatistics();
void information();
